[theme]
base = "dark"
primaryColor = "#43D17B"
backgroundColor = "#07110B"
secondaryBackgroundColor = "#0D1B12"
textColor = "#F1F7F3"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
