[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#060B18"
secondaryBackgroundColor = "#0C1730"
textColor = "#F7F9FF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
